# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14VohBn3zy8Vp6jjUWJ-RaWGnkkrr6YF5
"""

from google.colab import drive; drive.mount('/content/drive')
import pandas as pd
#load data
data = pd.read_csv('/content/drive/MyDrive/coffee_quality_project/coffee_ratings.csv')
print(data.head())