# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KferGbKqkOUCzOVUsMhf-TorthwsdhC1
"""

from google.colab import drive; drive.mount('/content/drive')
import pandas as pd
#load data
data = pd.read_csv('/content/drive/MyDrive/coffee_quality_project/coffee_ratings.csv')

#check data type and basic info
print(data.info())

#check missing values
print(data.isnull().sum())

#check duplicate values
print(data.duplicated().sum())

#generate statistical summary
print(data.describe())

#average rating
country_avg = data.groupby('country_of_origin')['total_cup_points'].mean()
print(country_avg)