# -*- coding: utf-8 -*-
"""Data Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KferGbKqkOUCzOVUsMhf-TorthwsdhC1
"""

from google.colab import drive; drive.mount('/content/drive')
import pandas as pd
#load data
data = pd.read_csv('/content/drive/MyDrive/coffee_quality_project/coffee_ratings.csv')

import seaborn as sns
import matplotlib.pyplot as plt

#check basic data statistics
data_stats = data['total_cup_points'].describe()
data_stats

#remove outliers (total_cup_points > 60)
data_cleaned = data[data['total_cup_points'] > 60]

#histogram of the rating distribution
plt.figure(figsize=(10, 6))
sns.histplot(data_cleaned['total_cup_points'], kde=True, bins=20)
plt.title("Distribution of Coffee Ratings (Cleaned)", fontsize=16)
plt.xlabel("Total Cup Points", fontsize=12)
plt.ylabel("Count", fontsize=12)
plt.show()

#top 10 countries with the largest number of samples
top_countries = data_cleaned['country_of_origin'].value_counts().head(10).index
top_country_data = data_cleaned[data_cleaned['country_of_origin'].isin(top_countries)]

#high sample country box plot
plt.figure(figsize=(12, 8))
sns.boxplot(data=top_country_data, x='country_of_origin', y='total_cup_points')
plt.title("Top 10 Countries by Coffee Ratings", fontsize=16)
plt.xlabel("Country of Origin", fontsize=12)
plt.ylabel("Total Cup Points", fontsize=12)
plt.xticks(rotation=45)
plt.show()

#low sample countries
low_sample_countries = data_cleaned['country_of_origin'].value_counts()
low_sample_countries = low_sample_countries[low_sample_countries < 10].index
low_sample_data = data_cleaned[data_cleaned['country_of_origin'].isin(low_sample_countries)]

#rating distribution of low sample countries
plt.figure(figsize=(12, 6))
sns.histplot(low_sample_data['total_cup_points'], kde=True, bins=10)
plt.title("Coffee Ratings for Low-Sample Countries", fontsize=16)
plt.xlabel("Total Cup Points", fontsize=12)
plt.ylabel("Count")
plt.show()