# -*- coding: utf-8 -*-
"""Heatmap

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KferGbKqkOUCzOVUsMhf-TorthwsdhC1
"""

from google.colab import drive; drive.mount('/content/drive')
import pandas as pd
#load data
data = pd.read_csv('/content/drive/MyDrive/coffee_quality_project/coffee_ratings.csv')

#filter invalid ratings
data_cleaned = data[data['total_cup_points'] > 60]

#filter numeric fields
numeric_data = data_cleaned.select_dtypes(include=['float64', 'int64'])

#check numeric fields
print(numeric_data.info())

#calculate the correlation matrix
correlation_matrix = numeric_data.corr()

#heatmap
plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, cmap='RdBu_r', fmt=".2f", annot_kws={"size": 8}, center=0)
plt.title("Correlation Heatmap of Coffee Ratings Data", fontsize=16)
plt.xticks(rotation=45, fontsize=10, ha='right')
plt.yticks(fontsize=10)
plt.show()